docs/faq.md

append 'https://' to be renderd as woking html-link to github project.

fix a url in doc

---

docs/explore.md

Fixed typos and minor errors in `explore.md`.

Fix explore.md

---

docs/building.md

Added instructions to build the project on macOS.

Instructions to build on macOS.

---

src/interpreter/vm.h

Removed redundant null if check

---

docs/faq.md

Add to FAQ why use C++

---

.vsts-ci.yml
src/rt/test/func/cowngc1/cowngc1.cc
src/rt/test/func/cowngc4/cowngc4.cc
testsuite/features/run-pass/binary-tree.verona

- Enable both Debug/Release testing of the language.
- Enable ASAN testing of the language.
- Enable runtime tests on macOS.
I was going to add a GCC configuration, but runtime tests are currently broken and it needs a non-trivial amount of work.
Fixes #41

Add more CI configurations

---

docs/debugging.md
src/rt/CMakeLists.txt
src/rt/test/systematic.h

Some rough notes on how to debug the various components on the system.
Needs more details, but should be a good starting point.

Information on debugging the runtime/interpreter/language.

---

testsuite/demo/run-pass/channel.verona

Building a channel from cowns, promises and queues.

Adding a Channel example

---

testsuite/CMakeLists.txt

Disable features/when test

---

.clang-format
.vsts-ci.yml
src/compiler/main.cc
src/compiler/source_manager.h
src/interpreter/main.cc

- Pulls snmalloc up-to-date.
- Fix the formatting.
- Ensure failures in CI gets reported.

Fixing formating, CI and snmalloc version.

---

src/rt/ds/barrier.h
src/rt/ds/stack.h
src/rt/sched/spmcq.h
src/rt/test/harness.h

Update snmalloc submodule

---

.vsts-ci.yml

If a PR only has changes in the docs/experiments directory or to markdown files, then we can ignore CI on this PR.

Make CI ignore changes to just doc or experiments.

---

CONTRIBUTING.md
README.md

GitHub seems more pleased that way and makes no difference in the end.

Move Contrib in its own document

---

.llvm-ci.yml
utils/azure/create-scale-set.sh

Updating LLVM's yaml file and Azure's scale set script.

Add Windows/Mac support for LLVM Build

---

utils/azure/create-scale-set.sh

Small change to allow different machines to be created

Azure script

---

docs/foreign_code.md
experiments/clang_interface/Makefile
experiments/clang_interface/README.md
experiments/clang_interface/clang_interface.cc
experiments/process_sandbox/CMakeLists.txt
experiments/process_sandbox/README.md
experiments/process_sandbox/example.cc
experiments/process_sandbox/functions.inc
experiments/process_sandbox/lib.cc
experiments/process_sandbox/library_runner.cc
experiments/process_sandbox/libsandbox.cc
experiments/process_sandbox/nosandbox.cc
experiments/process_sandbox/sandbox.hh
experiments/process_sandbox/shared.h

Also add a couple of experiments exploring parts of how this can work:
- A process-based sandbox using snmalloc for memory management.
- Some Clang code to explore interfacing with C++ via clang.

Initial documentation on how Verona / C++ interop should work.

---

devops/ci.yml
devops/nightly.yml

The GCC CI should be enabled once #165 is resolved.

Disable GCC CI

---

src/rt/ds/hashmap.h

The `const ObjectMap&` field resulted in the compiler not providing a copy constructor and copy assignment operator, even when setting them with `= default`. This PR changes the field to a pointer rather than defining those manually.

Allow default copy on ObjectMap iterator

---

src/rt/test/systematic.h

Unexpected symbol format would cause assertions on macOS to hang the process indefinitely rather than dump the flight recorder.

Handle macOS backtrace symbol format

---

devops/ci.yml
devops/llvm.yml
devops/nightly.yml

Detect cores on MacOs CI

---

docs/building.md

Fix reference to VERONA_EXTRA_CMAKE_ARGS in docs

---

src/rt/ds/asymlock.h

Feel free to suggest additional information.

Add minimal documentation for AsymmetricLock

---

src/rt/sched/backpressure.h

Update snmalloc
Add a noexcept annotation

Two small changes.

---

src/mlir/ast-utils.h
src/mlir/generator.cc
src/mlir/generator.h
testsuite/mlir/mlir-parse/call/mlir.txt
testsuite/mlir/mlir-parse/conditional.verona
testsuite/mlir/mlir-parse/conditional/mlir.txt
testsuite/mlir/mlir-parse/constant.verona
testsuite/mlir/mlir-parse/constant/mlir.txt
testsuite/mlir/mlir-parse/function.verona
testsuite/mlir/mlir-parse/function/mlir.txt
testsuite/mlir/mlir-parse/nested-conditional.verona
testsuite/mlir/mlir-parse/nested-conditional/mlir.txt
testsuite/mlir/mlir-parse/nested-while.verona
testsuite/mlir/mlir-parse/nested-while/mlir.txt
testsuite/mlir/mlir-parse/while-cont-brk.verona
testsuite/mlir/mlir-parse/while-cont-brk/mlir.txt
testsuite/mlir/mlir-parse/while-context.verona
testsuite/mlir/mlir-parse/while-context/mlir.txt
testsuite/mlir/mlir-parse/while-if.verona
testsuite/mlir/mlir-parse/while-if/mlir.txt
testsuite/mlir/mlir-parse/while.verona
testsuite/mlir/mlir-parse/while/mlir.txt

These two changes implement function prototypes and refactor the type handling of both arguments and return values and fixes the 'void return' TODO.

MLIR function refactory

---

src/rt/sched/cown.h

This brings the backpressure implementation up to date with the model, where overloaded or unmutable message participants result in the other participants becoming unmutable as well. This only applies when the fast send is interrupted, since that is the only time a recipient may be muted prior to running the message.

Update backpressure progress

---

src/mlir/generator.cc
testsuite/mlir/mlir-parse/conditional.verona
testsuite/mlir/mlir-parse/conditional/mlir.txt
testsuite/mlir/mlir-parse/while.verona
testsuite/mlir/mlir-parse/while/mlir.txt

This is something that was true early on but not anymore.

Allow constant conditionals

---

devops/ci.yml
testsuite/mlir/mlir-parse/dialect.mlir
testsuite/mlir/mlir-parse/lookup.mlir
testsuite/mlir/mlir-parse/subsumption.mlir

Add copyright check to MLIR files

---

CMakeLists.txt

@advancedwebdeveloper, is that clearer from our side?

Clarify clang-format message in CMake

---

src/rt/region/region_trace.h

This produces the exact same behaviour, only it makes use of an
existing higher abstraction.

Use a LinkedObjectStack to collect objects.

---

docs/.gitignore
docs/_config.yml
docs/_data/navbar.yml
docs/_includes/navbar.html
docs/_layouts/default.html
docs/_layouts/post.html
docs/_posts/2020-12-04-verona-project-blog.md
docs/assets/css/style.scss
docs/building.md
docs/debugging.md
docs/explore.md
docs/faq.md
docs/index.md
docs/news.html

This should be automatically rendered by GitHub Pages at:
https://microsoft.github.io/verona
You can test it locally by installing the github-pages gem and running
`jekyll serve` in the docs directory.

Add initial Verona web page.

---

docs/_data/navbar.yml

Content pages should be before tech pages. Also, fix a typo.

Reorder website navbar

---

devops/llvm-anybuild.yml

Update AnyBuild endpoint to use to align with the latest changes in the service

Update AnyBuildEnvironmentUri for AnyBuild LLVM pipeline

---

src/parser/ast.cc
src/parser/ast.h
src/parser/dispatch.h
src/parser/fields.h
src/parser/grammar.peg
src/parser/lexer.cc
src/parser/lexer.h
src/parser/parser-notes.md
src/parser/parser.cc
src/parser/resolve.cc
src/stdlib/controlflow/bind.verona
src/stdlib/controlflow/conditional.verona
src/stdlib/controlflow/controlflow.verona
src/stdlib/controlflow/loop.verona
src/stdlib/iterators/for.verona
src/stdlib/numbers/numbers.verona
src/stdlib/sequence/array.verona
src/stdlib/variadic/length.verona
testsuite/verona-parser/alloc.out/stdout.txt
testsuite/verona-parser/alloc.verona
testsuite/verona-parser/for-sugar.out/stdout.txt
testsuite/verona-parser/for-sugar.verona
testsuite/verona-parser/literal.out/stdout.txt
testsuite/verona-parser/literal.verona
testsuite/verona-parser/loop.out/stdout.txt
testsuite/verona-parser/strings.out/stdout.txt
testsuite/verona-parser/strings.verona
testsuite/verona-parser/typedef.out/stdout.txt
testsuite/verona-parser/typedef.verona

This adds type lists of the form `T...` to the parser. It also adds some uses of type lists to the stdlib.

Type lists

---

docs/internal/arithmetic.md
docs/internal/inheritance.md
docs/internal/object-memory.md

A very crude set of documents, not unlike the others in the same directory. It may contains some blatant errors, as this is just what I could write from our previous meetings. Feel free to correct me and propose better examples and descriptions.
I'm not sure how to categorise them, so I just created some random documents that we can refer back to later.
I'm hoping in due time we'll have a better set of design documents, organised and clear, but I don't think this is the right time, nor that I'm the right person (right now).
I'd be happy to create such document later, but I'd rather have the hind-sight of experience.

Add some internal documents

---

docs/internal/expressions.md

Another document, now on expressions.
This document has a lot of assumptions that we discussed on meetings, but also some that we didn't and I took the liberty of picking something that is familiar to me, not necessarily to the rest of the team. This means that, if something is odd, it's very likely wrong.
There are also a few examples missing, where I'm still a little confused about the syntax, not necessarily the semantics. Please offer suggestions for examples where none are provided.
As the document on types, this is WORK IN PROGRESS and not meant as a tutorial or user facing documentation. It's just a collection of ideas we mostly agree on, not a list of things we will discuss in the future.
In places where we need more discussion and the section is incomplete, I've added _notes_ to …

Adding expressions documentation

---

docs/internal/generics.md

This one is simpler but I may have missed a lot of content that Verona has more elaborate than Pony.
Again, happy to take in large suggestions.

Adding generics document

---

README.md

Adding syntax links

---

docs/internal/types.md

Adding module section, talking about visibility. Fixes #349?
Also adding a short description on `Self` types.
Also fixing typo

Adding module section, Self types

---

docs/internal/compiler-steps.md

This is more than a TODO list, it's a design document to make sure we're all in the same page as to what the passes are and what do we do in each stage.
I'm not expecting to be _right_ nor I'm expecting that everyone will _trust me_. I'm expecting people to have different views and promote discussion. But once we're in agreement, the document should reflect that agreement.
If later on we change our minds (amidst new evidence) we should update this document with a new PR.

Adding compiler steps document

---

docs/internal/dialect.md

This is a prototype created on top of my expectation of what the AST will look like when type inference is done, so there may be mismatches between what I wrote and what will eventually be.
Would be nice to spot obvious mistakes now, but I'm not expecting to finalise the design until we actually implement and see the problems first hand.

Adding dialect document

---

docs/building.md

Update building doc with deprecated path

---

README.md

README update with vim syntax

---

src/rt/object/object.h
src/rt/region/region_rc.h
src/rt/test/func/memory/memory_rc.h

This uses the lins cyclic reference counting algorithm: a local mark-scan of the subgraph of objects which are potentially cyclic. This cycle detection is based on two key observations: first, that cycles are formed only by interior object field references; and, second, if decrefing all such interior references causes a zero ref count on those objects, then it is a cycle.
The full algorithm is described here [1], but briefly, it works as follows: a stack of object pointers -- referred to as a "lins stack" -- is used as starting points to check for, (and remove), potential cycles. The lins stack is maintained by the region during incref/decref calls: an object is pushed when decrefing it yields a non-zero count; conversely, an object is removed from the lins stack when it is increfed.  The …

Implement cyclic reference counting

---

src/deprecated/interpreter/vm.cc
src/rt/cpp/vobject.h
src/rt/object/object.h
src/rt/pal/semaphore.h
src/rt/region/region.h
src/rt/region/region_api.h
src/rt/region/region_rc.h
src/rt/test/func/cownchain/cownchain.cc
src/rt/test/func/cowngc1/cowngc1.cc
src/rt/test/func/cowngc4/cowngc4.cc
src/rt/test/func/ext_ref/ext_ref_basic.h
src/rt/test/func/ext_ref/ext_ref_merge.h
src/rt/test/func/ext_ref_freeze/ext_ref_freeze.cc
src/rt/test/func/finalisers/finalisers.cc
src/rt/test/func/freeze/freeze.cc
src/rt/test/func/memory/memory.cc
src/rt/test/func/memory/memory.h
src/rt/test/func/memory/memory_alloc.h
src/rt/test/func/memory/memory_gc.h
src/rt/test/func/memory/memory_iterator.h
src/rt/test/func/memory/memory_merge.h
src/rt/test/func/memory/memory_rc.h
src/rt/test/func/memory/memory_swap_root.h
src/rt/test/func/noticeboard/noticeboard_basic.h
src/rt/test/func/noticeboard/noticeboard_weak.h
src/rt/test/func/rememberedset/rememberedset.cc
src/rt/test/harness.h
src/rt/test/perf/linkedlist/linkedlist.cc
src/rt/verona.h

Much is still needed.
* Debug features are not part of API.
* More operations need lifting into the API.
Primarily PRing this as it will help @jacob-hughes with his outstanding PRs.

First pass at creating a region API.

---

src/rt/object/object.h

New `Object`s should only be created by the runtime through the region
API.  The previous check required the constructor to be run for
`Object`.  This refactoring no longer requires the constructor for
`Object` to be run, but still detects if objects are created outside of
the runtime API such as the `new` overload provided in `vobject.h`.

Change validation of new objects

---

experiments/process_sandbox/include/process_sandbox/helpers.h
experiments/process_sandbox/include/process_sandbox/platform/platform.h
experiments/process_sandbox/include/process_sandbox/sandbox.h
experiments/process_sandbox/src/child_malloc.h
experiments/process_sandbox/src/host_service_calls.h
experiments/process_sandbox/src/library_runner.cc
experiments/process_sandbox/src/libsandbox.cc
src/deprecated/interpreter/object.cc
src/rt/ds/bag.h
src/rt/ds/barrier.h
src/rt/ds/hashmap.h
src/rt/ds/morebits.h
src/rt/ds/mpscq.h
src/rt/ds/stack.h
src/rt/object/object.h
src/rt/pal/cpu.h
src/rt/region/externalreference.h
src/rt/region/region_trace.h
src/rt/region/rememberedset.h
src/rt/sched/behaviour.h
src/rt/sched/cown.h
src/rt/sched/epoch.h
src/rt/sched/multimessage.h
src/rt/sched/schedulerstats.h
src/rt/sched/schedulerthread.h
src/rt/sched/threadpool.h
src/rt/sched/threadstate.h
src/rt/test/logging.h
src/rt/test/systematic.h
src/rt/verona.h

This is currently using the microsoft/snmalloc#501 in the submodule.  It
will track that until merged.

Update for new snmalloc.

---

experiments/process_sandbox/include/process_sandbox/sandbox.h
experiments/process_sandbox/src/host_service_calls.h
experiments/process_sandbox/src/libsandbox.cc
experiments/process_sandbox/tests/CMakeLists.txt
experiments/process_sandbox/tests/sandbox-rpc-bounds.cc
experiments/process_sandbox/tests/sandboxlib-rpc-bounds.cc

Also add a test to make sure that it stays fixed.

Fix a bug in bounds checking that @saaramar found.

---

experiments/process_sandbox/src/libsandbox.cc

This function takes a `hint` parameter that uses the same structure as
the return type, but ignores all except for four fields.  The others are
required to be null.
It is possible that a buggy implementation of the checker could
try to dereference the pointer fields.  By zeroing them at the boundary,
we add some defence in depth.
@saaramar concluded that this was not currently a security issue but the
fact that it showed up on his review at all suggests that the security
properties of the code are insufficiently clear, since the existing code
was safe only in the presence of the specific behaviour of the callee
implementation.

Add some defence in depth for the getaddrinfo host call.

---

experiments/process_sandbox/src/libsandbox.cc

Addresses the confusion in #563

[NFC] Add a comment about metadata ownership.

---

experiments/process_sandbox/include/process_sandbox/sandbox.h
experiments/process_sandbox/include/process_sandbox/shared_memory_region.h
experiments/process_sandbox/src/libsandbox.cc
experiments/process_sandbox/tests/sandboxlib-rpc-bounds.cc

Includes a test case derived from @saaramar's example.
Fixes #562

Add some missing checks.

---

src/rt/test/func/external_event_source/external_event_source.cc

This makes the lifetime of the event source allocation a shared_ptr to
make the lifetime clearer.  This was giving memory leaks previously
#552, but I was no able to replicate locally.

Event source lifetime with SharedPtr

---

.github/workflows/update-snmalloc.yaml
experiments/process_sandbox/include/process_sandbox/callback_numbers.h
experiments/process_sandbox/include/process_sandbox/cxxsandbox.h
experiments/process_sandbox/include/process_sandbox/platform/socketpair_posix.h
experiments/process_sandbox/include/process_sandbox/sandbox.h
experiments/process_sandbox/src/library_runner.cc
experiments/process_sandbox/src/libsandbox.cc
experiments/process_sandbox/tests/sandbox-zlib.cc
experiments/process_sandbox/tests/sandboxlib-rpc-deadlock.cc
experiments/process_sandbox/tests/socketpair-sendhandle.cc

Two commits that should fix #583, #584, #586, and #588.
Kept as two commits for (maybe) easier review.
@saaramar, please can you take a look?

Security fixes

---

src/rt/test/perf/smallbank/args.h
src/rt/test/perf/smallbank/smallbank.cc

This PR implements the smallbank transactional benchmark using Verona cowns.

Add Smallbank experiment

---

experiments/process_sandbox/include/process_sandbox/sandbox.h
experiments/process_sandbox/src/child_malloc.h
experiments/process_sandbox/src/library_runner.cc
experiments/process_sandbox/src/libsandbox.cc
src/rt/test/perf/smallbank/args.h

* Update snmalloc to latest commit. 
* Fix a compilation error on Windows.

Minor updates

---

experiments/process_sandbox/CMakeLists.txt
experiments/process_sandbox/include/process_sandbox/helpers.h

libfmt changed a bunch of things, snmalloc is no longer in the tree.

Fix the process sandbox.

---

.github/workflows/cmake.yml

https://github.com/actions/runner-images/issues/8659

Update CI workaround.

---

docs/_data/navbar.yml
docs/publications.md
docs/pyrona.md

This adds some documentation to help talk about Pyrona with people at the Language Summit.

Add some Pyrona notes to the website for the Language summit.
