microsoft/verona

docs/faq.md

Pony language has an official website. To make documentation more consistent (looking at Rust and Cyclone examples) I propose to use the official website link instead of the GitHub account link in the current version of FAQ.

Change Pony language link to official website

---

.clang-format

I found that my local clang-format tool was reformatting files to be inconsistent with the existing style for braces after case labels. This makes the rule explicit in `.clang-format`.

clang-format: Add break after case label

---

src/compiler/fs.h
src/compiler/main.cc
testsuite/features/compile-pass/library/child.verona
testsuite/features/compile-pass/use.verona

Currently the following code:
```rust
// foo.verona
use "bar.verona"
```
```java
// bar.verona
class Main {
main() {}
}
```
and running `veronac foo.verona` will produce the following error:
```
Cannot open file ""/bar.verona""
```
You can only run a file with dependencies, from the current directory, if you prepend it with a `./`.
For example this, `veronac ./foo.verona`, works perfectly fine.
This PR makes it so that is no longer required.

Support relative importing without requiring "./" in the input file path

---

src/rt/test/func/cowngc1/cowngc1.cc
src/rt/test/func/cowngc4/cowngc4.cc
src/rt/test/func/diningphilosophers/diningphil.cc
src/rt/test/harness.h

The `seed` field was uninitialized on the construction of `SystematicTestHarness`. This has resulted in the use of uninitialized values for the xoroshiro PRNG in multiple runtime tests.

Remove uninitialized field from rt test harness

---

docs/building.md

Applied the proper cmake flags to set the C and C++ compiler.
```
CC=...
CXX=...
```
These environment variables can have side effects for the rest of the system, it's better to have cmake use it for 1 specific build.

Cmake now uses a flag rather than environment variables

---

src/compiler/main.cc

There was a c-style cast in the main.cc file which, in the future, could possibly discard const qualifiers.
Future proofing :)

Resolved an issue where in the future cv qualifiers could be ignored

---

src/compiler/codegen/reachability.cc
testsuite/reachability/compile-pass/visit-variable-renaming-type.verona

Loops introduce variable renamings and their types. The
reachability pass doesn't need to do anything here but
that visitor needs a variable renaming type case.
Fixes #67

Fix issue #67

---

.vsts-ci.yml
src/compiler/main.cc
src/interpreter/main.cc
testsuite/common.cmake

This makes the veronac and interpreter output exceptions
and not produce a dialog box on Windows for debugging
when inside a CI build.

Made Verona CI build output stack traces on crashs

---

.clang-format
.vsts-ci.yml
src/compiler/fs.h
src/compiler/intern.cc
src/compiler/parser.cc
src/interpreter/vm.h
src/rt/test/func/rememberedset/rememberedset.cc
src/rt/test/perf/epoch/epoch.cc
testsuite/features/compile-pass/library/child.verona
testsuite/features/compile-pass/library/sibling.verona
testsuite/features/compile-pass/use.verona
testsuite/features/run-pass/operators.verona
testsuite/resolution/compile-fail/builtin-body.verona
testsuite/resolution/compile-fail/module.verona
testsuite/resolution/compile-fail/module/child.verona

Fixing some bugs in CI. 
* Make checks for copyright/license in files
* Move to clang-format-9.

Fixes to CI.

---

src/compiler/codegen/codegen.cc
src/interpreter/bytecode.h
src/interpreter/code.h

This is #76 updated to the with fixes to the CI and formatting.

Yuhanun feature/bytecode magicnum

---

src/interpreter/vm.cc

The STORE opcode is never valid on an IMM reference, so we can
disallow that. Additionally when writing a MUT value, the regions of
the two objects must match.
In practice the first check should never fail as the compiler will
disallow this statically. The second can happen as the compiler
doesn't enforce region equality yet, so it's nice to have a dynamic
check.

Make the VM stricter about field writes

---

src/interpreter/object.cc
src/interpreter/object.h
src/interpreter/vm.cc
src/interpreter/vm.h
src/rt/cpp/vobject.h
src/rt/object/object.h
src/rt/region/freeze.h
src/rt/region/immutable.h
src/rt/region/region.h
src/rt/region/region_arena.h
src/rt/region/region_base.h
src/rt/region/region_trace.h
src/rt/sched/cown.h
src/rt/test/func/cown_weak_ref/cown_weak_ref.cc
src/rt/test/func/cowngc1/cowngc1.cc
src/rt/test/func/cowngc4/cowngc4.cc
src/rt/test/func/diningphilosophers/diningphil.cc
src/rt/test/func/finalisers/finalisers.cc
src/rt/test/func/memory/memory.h
src/rt/test/func/memory/memory_iterator.h
testsuite/features/run-pass/finalisers-extract.verona

This adds a desctructor to every object. The destructor runs just before an object is deallocated. The VM uses this destructor to deallocate the array of fields, allowing us to move the "find iso fields" phase to after the finaliser has run.
Fixes #62.

Fix the "extract in finaliser" pattern.

---

src/interpreter/vm.cc
src/interpreter/vm.h

- The current frame is stored at the top of the CF stack, rather than
as a separate field.
- The current ip is stored in the top most frame, avoiding the need to
save / restore it on call / return.
- Frames have a "halt on return" flag, used to make the return opcode
in finalisers return control to the C++ code.
- Remove ident_. It can be inferred from the size of the cf stack.
This was prompted by a bug in the way finalisers used to be dispatched.
The receiver of the finaliser would be written to the last register of
the current frame. This could overwrite useful values, or underflow
and try to write to register 255, causing a crash. We were getting a
flaky CI because of it.

Simplify the CF stack and finalisers implementation.

---

testsuite/CMakeLists.txt

It gets stuck in a solver loop every 1 in ~200 runs, with a trace that
looks very similar to the already disabled features/run-pass/when test.
See #77

Disable features/run-pass/loop test.

---

src/rt/CMakeLists.txt

The test generation for CI is problematic.  When the CHUNK size was
made larger for the testing it meant the systematic test names no longer
match the regexp for making a smaller set of running tests in CI.
This test reduces the batch size in CI, so the original regexp still
works.

Fixed test generation of CI

---

src/rt/test/func/cowngc1/cowngc1.cc
src/rt/test/func/cowngc4/cowngc4.cc

This PR fixes a compilation error by moving the declaration of `CCown` from cowngc1 and cowngc4 tests before its use as a class derrived from `Object`.

Fix error when compiling RT tests

---

src/interpreter/bytecode.h

Missing include <limits> generated the error:
```
../src/./interpreter/bytecode.h:124:10:
error: no member named 'numeric_limits' in namespace 'std'
std::numeric_limits<DescriptorIdx>::max();
```

Fix compilation error with clang 10

---

CMakeLists.txt
docs/building.md

Just running `ctest` can silently crash if the user hasn't also ran
`ninja install`, which is confusing. This commit adds a new `check`
target that not only makes the dependency clear, but also defaults the
test to run on the maximum number of cores available.
Fixes #114

Add `ninja check` target to run ctest with deps

---

.gitmodules
CMakeLists.txt
src/CMakeLists.txt
src/ast/CMakeLists.txt
src/ast/ast.cc
src/ast/ast.h
src/ast/cli.cc
src/ast/cli.h
src/ast/err.cc
src/ast/err.h
src/ast/files.cc
src/ast/files.h
src/ast/grammar.peg
src/ast/main.cc
src/ast/parser.cc
src/ast/parser.h
src/ast/path.cc
src/ast/path.h
src/ast/sym.cc
src/ast/sym.h

This uses cpp-peglib to generate a packrat PEG for a grammar defined
in a text file, and then does some very basic AST manipulation. It
sets up scopes and symbol tables, and does a bit of fixity analysis.
The intention is to use this for a very slim parser front-end that
goes to MLIR before any serious heavy lifting is done. No tests are
included in the initial commit, as the grammar.peg is preliminary.Z

Initial commit for a cpp-peglib based parser and untyped AST gen

---

src/rt/sched/epoch.h
src/rt/sched/multimessage.h
src/rt/sched/schedulerthread.h
src/rt/sched/spmcq.h

This PR fixes the documentation and naming of the spmcq implementation to be more consistent with the mpscq. Statically known alloc and dealloc sizes are also passed to snmalloc for `MultiMessage` and epoch `DecNode`.

Sched fixup

---

.vsts-ci.yml

The runtime systematic testing can be slow, and there are a lot of
language changes that do not need to retest the runtime. This changed
detects if anything has changed in the runtime, and if it has not
changed, then it does not rebuild or run the tests.

Only build and test runtime if changed

---

src/rt/sched/cown.h
src/rt/sched/schedulerthread.h

Make the ref count the trigger for final collection on a cown.  Leak
detection can trigger the body of the cown to be collected, but
the stub will remain until the weak_count hits 0.  This fixes a bug
where the delayed dec ref lists are ignored by the leak detector. Now
when the leak detector frees an unreachable component, it performs the
decrefs, but does not signal that the stub can be collected until the
ref count reachs zero.
Previously, the thread field was set to zero to indicate the body had
been collected, now we use the bottom bit, so we don't confuse the
unadopted by a scheduler thread state, and the collected state.

Fix potential double collection

---

src/ast/CMakeLists.txt
src/ast/ast.cc
src/ast/ast.h
src/ast/grammar.peg
src/ast/lit.cc
src/ast/lit.h
src/ast/main.cc
src/ast/prec.cc
src/ast/prec.h
src/ast/sym.cc
testsuite/parse/ast-parse/literal.verona
testsuite/parse/ast-parse/literal/ast.txt
testsuite/parse/ast-parse/strings.verona
testsuite/parse/ast-parse/strings/ast.txt

This PR changes from `(...) syntax to allow two forms of string
literal:
1. C-style strings, which are "..." delimited, not nested, not
interpolated, and allow C-style escapes. Unlike C strings, they
are multiline and allow arbitrary UTF-8 content.
2. Verona strings, which are "{...}" delimited, nested, have no
escapes at all, and interpolate $id and ${expr} in the outer-
most nesting. They are also multiline (and do indentation
mangling), and allow arbitrary UTF-8 content.

String literals

---

src/interpreter/object.cc
src/interpreter/object.h
src/interpreter/vm.cc
src/rt/cpp/vobject.h
src/rt/object/object.h
src/rt/region/externalreference.h
src/rt/region/region_arena.h
src/rt/region/region_base.h
src/rt/region/region_trace.h
src/rt/sched/cown.h

The anonymous union types in Verona and snmalloc were not compiling on VS2019 due to a lack of default constructor. I could not find a way to add a default constructor to an anonymous union. This addresses those issues by making the unions types have default constructors.

VS 2019 fixes

---

.gitmodules

This speeds up CI builds as it only checks out the last commit status.
We shouldn't have to submit any changes to the external repositories via
Verona anyway, so it should be good long term.

Mark all submodules as 'shallow'

---

src/rt/ds/hashmap.h
src/rt/object/object.h
src/rt/region/externalreference.h
src/rt/region/rememberedset.h

This PR makes several fixes and simplifications to the user interface of the Robin Hood hash map:
- Use `uintptr_t` instead of `size_t` when messing with `Object*` key bits
- Replace entry wrapper classes and `key_of` with a single set of defaulted static callbacks
- Enforce strict entry types
- Hide manipulation of `Object*` key bits from the user
- Add overload for insert without the need to create a dummy index

Refactor hashmap

---

src/rt/ds/hashmap.h
src/rt/object/object.h
src/rt/region/externalreference.h
src/rt/region/region_arena.h
src/rt/region/region_trace.h
src/rt/region/rememberedset.h
src/rt/test/func/hashmap/hashmap.cc

This PR makes several improvements over the initial implementation of
the hashmap. These improvements include documentation of member
functions and the internal algorithm used for the implementation. Tests
have also been added to compare the correctness of the map against the
standard `unordered_map` on randomized sequences of insert, update, and
delete operations.

Rewrite object hashmap

---

CMakeLists.txt
devops/ci.yml
devops/nightly.yml

This option enables asserts without the need of a debug build. The
implementation is stolen from LLVM because it's not trivial.
With the new flag, we enable assertions on all CI and nightly builds.
LLVM builds already had assertions enabled before.

Add ENABLE_ASSERTS to cmake

---

.gitmodules
devops/ci.yml
devops/llvm.yml
devops/nightly.yml
src/CMakeLists.txt
src/ast/CMakeLists.txt
src/mlir/CMakeLists.txt
src/mlir/README.md
src/mlir/ast-utils.cc
src/mlir/ast-utils.h
src/mlir/dialect/CMakeLists.txt
src/mlir/dialect/VeronaDialect.cc
src/mlir/dialect/VeronaDialect.h
src/mlir/dialect/VeronaDialect.td
src/mlir/dialect/VeronaOps.cc
src/mlir/dialect/VeronaOps.h
src/mlir/dialect/VeronaOps.td
src/mlir/generator.cc
src/mlir/generator.h
src/mlir/symbol.h
src/mlir/verona-mlir.cc
testsuite/CMakeLists.txt
testsuite/README.md
testsuite/mlir-parse.cmake
testsuite/mlir/mlir-parse/dummy.mlir
testsuite/mlir/mlir-parse/dummy/out.mlir
testsuite/mlir/mlir-parse/function.verona
testsuite/mlir/mlir-parse/function/out.mlir
testsuite/update-dump.cmake
utils/llvm/setup-llvm-builddir.sh

This is the initial prototype for the MLIR lowering from Verona code.
It has the main features:
1. Creates an MLIR Generator, that transforms the AST into MLIR nodes. For now it can only lower one file, `function.verona` and does so in an opaque MLIR format (no dialect). It does not have a dialect yet.
2. A prototype of a dialect, empty, but with the minimal structure of an out-of-tree dialect to follow up when we start having proper Verona nodes.
3. A thin layer between AST and MLIR, to help convert the semantics between the two. It's far from complete, but it's an idea on how we should interface these two completely different representations.
4. Adds a LIT + FileCheck testing structure with 3 tests (including `function.verona`).
5. Adds an LLVM build CI loop, where we cache the LLVM …

MLIR prototype

---

docs/building.md
utils/llvm/setup-llvm-builddir.sh

Since our CI was downloading before running the script, this went unnoticed when we moved from Azure Universal Package to blob storage. I have tested on Linux, and there's no reason not to work on Mac, but I can't make it work on my Windows, even though it works on the CI's Windows.

Fix llvm script to download from the blob, not universal package

---

src/mlir/ast-utils.cc
src/mlir/ast-utils.h
src/mlir/generator.cc
testsuite/mlir/mlir-fail/operator.verona

This removes every dependency that the MLIR generator had on the
AST structure. All searches in the AST structure and accessors to names,
IDs, types are done via helper functions.
The only knowledge of the AST is via a NodeKind switch in parseNode,
which is a lot better than calling "isFoo" and "isBar" functons, but it
could be made so if people feel strongly inclined. Given that this is a
helper enum, not an AST enum, it should be ok.
The logic for accessing the AST structure is now 100% encoded in the
helper functions and comments were added where things were less than
clear. This makes it easier for us to exchange knowledge and refine the
API of both AST and MLIR to make things simpler.

Refactor MLIR generator to use ast_utils for all AST handling

---

devops/ci.yml
devops/nightly.yml

Some builds recently failed because the Mac builders were too slow and the RT tests were too long. Ramping up timeouts to 2hs and hopping the free builders can cope with it.

Force 2h timeout for all builds

---

src/mlir/ast-utils.cc
src/mlir/ast-utils.h
src/mlir/generator.cc
src/mlir/generator.h
src/mlir/symbol.h
testsuite/mlir/mlir-parse/while-cont-brk.verona
testsuite/mlir/mlir-parse/while-cont-brk/mlir.out
testsuite/mlir/mlir-parse/while-context.verona
testsuite/mlir/mlir-parse/while-context/out.mlir
testsuite/mlir/mlir-parse/while-if.verona
testsuite/mlir/mlir-parse/while-if/out.mlir
testsuite/mlir/mlir-parse/while.verona
testsuite/mlir/mlir-parse/while/mlir.out

While implementing simple while blocks, I realised the variable context for lexical blocks wasn't pushing new frames when entering if/else blocks, which were also needed when entering loop blocks. This PR fixes that problem and implements simple while loops with conditionals, continue and break.
Not supported yet: nested loops. I need to do the refactor of the BranchOp / Value return that I mention in the TODO. This will be done next.
The patches can be reviewed as one or individually.
Continues to implement #117.

Implement while blocks, improve conditional support and lexical contexts

---

CMakeLists.txt
src/CMakeLists.txt

With the introduction of ExternalProject, the clangformat target was
being picked for the outer build using a special `VERONA_MINIMAL_CMAKE`
flag.
In addition to being overly complicated, this did not expose the target
for builds that manually specified a `-DVERONA_LLVM_LOCATION` flag.
We can fix that by moving the target to the top-level CMakeLists file,
making it independent of the LLVM build strategy.

Move definition of clangformat target to toplevel

---

src/mlir/ast-utils.cc
src/mlir/ast-utils.h
src/mlir/generator.cc
src/mlir/generator.h
testsuite/mlir/mlir-parse/call.verona
testsuite/mlir/mlir-parse/call/out.mlir

Changing how to detect basic-block termination to account for all known
terminators and empty basic blocks, so we don't need to terminate blocks
that have already been handled.
Implementing return values (of single expressions) as well as function
calls with the appropriate casts for the arguments, given we don't yet
know all types at this time.
If Verona accepts multiple return values, we'll need to change the
return value of all `parseX` functions to a vector of values. This
should be done later, as a refactor PR with examples. It will also fix
the `return mlir::Value()` problem, as we can return an empty list.
(ref. #117)

Adding support for function calls and return values

---

testsuite/mlir/mlir-parse/nested-while.verona
testsuite/mlir/mlir-parse/nested-while/out.mlir

Left over from last implementation.
This will change soon to use a custom dialect operation for while loops when we lower for loops as while loops, but it's good to have the test here to make sure we can still parse the AST correctly into the right MLIR structure. (See #203).

[NFC] Test for nested while loops

---

src/mlir/generator.cc

Otherwise we would be proceeding with a null pointer.
Additionally parseSourceFile already runs the verifier, so no point in running it again ourselves.

Bail out on MLIR parsing errors.

---

devops/ci.yml
devops/llvm.yml
devops/nightly.yml

Other than updating CMake, the change brings 4000-ish commits closer to trunk and breaks nothing else.

LLVM update to 6ce97eee354

---

src/mlir/CMakeLists.txt
src/mlir/driver.cc
src/mlir/driver.h
src/mlir/generator.cc
src/mlir/generator.h
src/mlir/verona-mlir.cc

This moves the MLIR/LLVM pipeline logic out of the generator and into
a new class. The Generator is now only responsible for AST->MLIR
conversion.
This will be helpful as we start adding more passes, and the logic to
handle those becomes more complicated.

Add a driver class responsible for running passes.

---

src/mlir/dialect/VeronaOps.cc
src/mlir/dialect/VeronaOps.td

Class operations' regions shouldn't accept any arguments. Rather than
have custom logic for it, we can use upstream's new NoRegionArguments
trait.

Use the new NoRegionArguments trait.

---

CMakeLists.txt

Passes `-j` flag to `ctest`.
Addresses part of #198.

Parallel Verona tests

---

CMakeLists.txt

We can't control how much to log, the options are either every percent
or nothing. 100 lines on the build is annoying enough, but the lines
go to stderr and the CI logs them as "errors" polluting the reports.
Another #198 check.

Make Quiet LLVM download the default option

---

CMakeLists.txt
devops/llvm.yml
src/mlir/CMakeLists.txt

LLVM Build: https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=1364&view=results
All MD5 files are in the container, Verona build works nicely with and without the archive.

Use MD5 hash to avoid downloading LLVM every time

---

README.md

As mentioned in #181 we don't need to have different pipelines to show different badges for each build type.

Update build matrix with specific types of builds

---

docs/debugging.md
src/interpreter/interpreter.cc
src/rt/ds/morebits.h
src/rt/ds/scramble.h
src/rt/object/object.h
src/rt/sched/base_noticeboard.h
src/rt/sched/cown.h
src/rt/sched/epoch.h
src/rt/sched/schedulerthread.h
src/rt/sched/threadpool.h
src/rt/test/func/diningphilosophers/diningphil.cc
src/rt/test/func/ext_ref_freeze/ext_ref_freeze.cc
src/rt/test/func/scramble/scramble.cc
src/rt/test/harness.h
src/rt/test/perf/backpressure1/backpressure1.cc
src/rt/test/perf/backpressure2/backpressure2.cc
src/rt/test/perf/backpressure3/backpressure3.cc
src/rt/test/perf/ubench/ubench.cc
src/rt/test/systematic.h

This change is made primarily to allow Object IDs to be a scrambled
permutation when systematic testing is enabled.

Move RNG and Scrambler to systematic namespace

---

CMakeLists.txt
devops/ci.yml
devops/nightly.yml
docs/building.md
external/CMakeLists.txt

Address some sub-issues in #198.
* Automatically pass compiler to subprojects
* Fixes bug introduced in #233 that didn't correctly generate subprojects for Verona (RelWithDebInfo, Debug).

Fixes to CI

---

src/mlir/driver.cc
src/mlir/driver.h

This gives us a bit of colour, prints the relevant piece of code, and
displays notes attached to diagnostics.

Add a diagnostic handler for prettier error messages.

---

src/rt/sched/cown.h
src/rt/test/func/cownchain/cownchain.cc
src/rt/test/func/memory/memory.h
src/rt/test/func/memory/memory_subregion.h

Recursively deallocating structures if implemented incorrectly can cause a stack overflow.  This PR adds twos test
* Deeply nested region test - very long chain of traceable regions
* Deeply nested cown test - very long chain of cowns going via a region at each level
The PR also fixes the deeply nested cowns code to queue recursive calls to avoid stack overflow.

Recusive deallocation tests and fixes

---

CMakeLists.txt

The last change to the CI mechanism, passing all commands Verona were
overwriting the value set directly in the project. Now, all the options
we want in Verona need to be passed globally and only globally.

Fix compile_commands change after CI refactor

---

src/rt/sched/backpressure.h
src/rt/sched/cown.h
src/rt/sched/schedulerthread.h

On `fast_send` the unacquired cowns required for a multi-message are made unmutable if any are overloaded. This continues to cover cases where an overloaded cown, `a`, mutes another cown, `b`, and then requires `b` in a future message. But now cowns are set unmutable only prior to a fast acquire loop.

Backpressure: set unmutable on fast_send

---

src/mlir/generator.cc
testsuite/mlir/mlir-parse/call.verona

This makes sure the returned value is of the same type as the region
needs it to be. This is a copy of the implicit function return, and we
need to common them up, but they come from different AST nodes, where
one is implicit.
Given we're not yet completely sure on what we'll do with returns, this
refactory can be done later, with the risk of being irrelevant soon.

Add cast on return

---

src/mlir/dialect/Typechecker.cc
src/mlir/dialect/Typechecker.h
src/mlir/dialect/VeronaOps.cc
src/mlir/dialect/VeronaTypes.cc
src/mlir/dialect/VeronaTypes.h
testsuite/mlir/mlir-parse/subsumption.mlir
testsuite/mlir/mlir-parse/subsumption/out.mlir

This helps recognise distributivity of joins over meets, such as:
meet<A, join<B, C>> <: join<meet<A, B>, meet<A, C>>
While distributivity of joins over meets alone is quite niche, and
many languages get away without supporting it, distributivity over
viewpoint types (which will be added soon) is a lot more critical.
This PR lays the ground work for that.

Normalize types before applying subtyping rules.

---

src/rt/sched/threadpool.h
src/rt/test/func/runtimepause/runtimepause.cc
src/rt/test/perf/backpressure1/backpressure1.cc
src/rt/test/perf/ubench/ubench.cc

This change replaces the boolean that enables runtime teardown with an
atomic counter of external event sources. This is necessary to support
asynchronous I/O events in the runtime.

Prevent teardown with external event source count

---

src/mlir/ast-utils.h
src/mlir/generator.cc
src/mlir/generator.h
testsuite/mlir/mlir-parse/for.verona
testsuite/mlir/mlir-parse/for/mlir.txt
testsuite/mlir/mlir-parse/function.verona
testsuite/mlir/mlir-parse/function/mlir.txt

This introduces `for` loops as MLIR constructs, similar to `while` but with the additional iteration handling.
A few following commits fix some issues found when calling functions (extra casts, no return values, arg types without args).
Depends on #252.
Fixes #203.

Implement for loops in MLIR

---

src/mlir/ast-utils.h
src/mlir/generator.cc

The header has no guard and would break compilation if used twice.
However, we also need to move it to a static struct, as the functions
would be defined twice, and break linkage.
This wasn't a problem before, when the header only declared the
functions (and ast-utils.cc would define them), but since we moved
implementation to the header (due to the use of templates on array
filling functions), we now have all definitions in the header.
This is a non-functional-change, that just makes it safer to use the
ast-utils on other files, when needed.
Needs to be applied on top of #256 for ordering issues.

[NFC] Add pragma once to ast-utils.h

---

src/ast/grammar.peg
src/mlir/ast-utils.h
src/mlir/generator.cc
testsuite/mlir/mlir-parse/constant.verona
testsuite/mlir/mlir-parse/constant/mlir.txt
testsuite/parse/ast-parse/literal.verona
testsuite/parse/ast-parse/literal/ast.txt

This makes the bool type like the others for constants, changing the AST
node from "true (true)" to "bool (true)", which makes more sense.
Also adding parsing rules to the MLIR generator to accept those constant
types.
Fixes #253

Add bool type in grammar, constants in MLIR

---

src/mlir/abi.h
src/mlir/generator.cc
src/mlir/generator.h
testsuite/mlir/mlir-parse/for.verona
testsuite/mlir/mlir-parse/for/mlir.txt

This is a large change, moving a lot of code from repeated patterns in the parsers into more generic functions creating the MLIR nodes. But the functionality is still identical, and therefore, no new tests. The only change in the output is the unnecessary declaration of "for" loop iteration methods that are now automatically declared.
The purpose of this change is to:
* Allow code reuse for compiler generated sequences, like `for` loops, `lambda`s, etc.
* Allow code reuse across AST parsers (ex. `break` & `continue`, `load` and `store`, `constant`s, etc).
* Introduce an ABI+Lowering layer to carry language-specific concepts independent of the lowering.
The ABI side isn't complete, by far. It's just a prototype of what we want to do. When we have a more complete Verona dialect (with …

Generator refactory, splitting AST parsers from MLIR generators

---

src/mlir/ast-utils.h
src/mlir/dialect/VeronaDialect.cc
src/mlir/dialect/VeronaTypes.cc
src/mlir/dialect/VeronaTypes.h
src/mlir/generator.cc
src/mlir/generator.h
testsuite/mlir/mlir-parse/call/mlir.txt
testsuite/mlir/mlir-parse/conditional/mlir.txt
testsuite/mlir/mlir-parse/dialect.mlir
testsuite/mlir/mlir-parse/dialect/mlir.txt
testsuite/mlir/mlir-parse/for.verona
testsuite/mlir/mlir-parse/for/mlir.txt
testsuite/mlir/mlir-parse/function/mlir.txt
testsuite/mlir/mlir-parse/nested-conditional/mlir.txt
testsuite/mlir/mlir-parse/nested-while/mlir.txt
testsuite/mlir/mlir-parse/types.verona
testsuite/mlir/mlir-parse/types/mlir.txt
testsuite/mlir/mlir-parse/while-cont-brk/mlir.txt
testsuite/mlir/mlir-parse/while-context/mlir.txt
testsuite/mlir/mlir-parse/while-if/mlir.txt
testsuite/mlir/mlir-parse/while/mlir.txt

Not yet converting `where` types to proper Verona types, but all others (integer, float, join, meet) including nested operations.
Added Float and Bool types in the dialect to complete the support needed for this change.
Fixes #274

Generating verona types from AST

---

devops/ci.yml
devops/nightly.yml
src/interpreter/object.cc
src/rt/cpp/vobject.h
src/rt/ds/hashmap.h
src/rt/object/object.h
src/rt/region/externalreference.h
src/rt/region/region_arena.h
src/rt/region/region_base.h
src/rt/region/region_trace.h
src/rt/sched/cown.h
src/rt/test/systematic.h

GCC was applying dead-store-eliination to the region-meta data
as it was part of Object, and assigned before the C++ constructor.
This changes the representation of Object, to not contain the meta
data, but access the meta-data directly before the Object.
There are some defensive code paths to try to ensure that each Object*
actually has the meta-data before it.

Refactor to store meta-data before Object*

---

src/mlir/ast-utils.h
src/mlir/generator.cc
src/mlir/generator.h
testsuite/mlir/mlir-parse/class.verona
testsuite/mlir/mlir-parse/class/mlir.txt

This lowers classes as the existing dialect operator and type. I'm following the existing `dialect.mlir` file for syntax and I can make it agree on the class definition.
Part of this work was also lowering `new`, `view` and fields access, but that may need changes to the dialect representation, so I'll leave it for the next PR, after we have discussed it properly.
Working towards #280

Lowers classes as ops/types

---

src/interpreter/format.h
src/rt/object/object.h
src/rt/sched/schedulerthread.h

All systematic logs would previously show the address of objects, instead of the object identifier generated under systematic testing. This PR adds an overload for the stream operator so that `const Object*` is displayed as the ID under systematic testing.

Show object ID in systematic logs

---

src/mlir/generator.cc
src/mlir/generator.h
testsuite/mlir/mlir-parse/for.verona
testsuite/mlir/mlir-parse/for/mlir.txt

Changes for loop from
```
while ($iter.has_value())
val = $iter.apply()
$iter.next()
[body]
```
to
```
while ($iter.has_value())
val = $iter.apply()
[body]
$iter.next()
```
There is additional complexity to deal with continue, which must call `next`.

Make `next` call at end of `for` loop

---

src/rt/sched/schedulerthread.h

This PR removes prevents a log message in the scheduler from attempting to show an invalid epoch mark in the case that the cown popped from the scheduler queue is the token.

Fix log message for rescheduled cown

---

src/rt/sched/cown.h
src/rt/sched/status.h

This PR replaces the use of bit fields for tracking cown status. The added separation of the `_load_hist` and `_current_load` fields prevents the clang SLP vectorizer from optimizing the `total_load()` operation into AVX2 instructions. Based on some profiling of the backpressure system, this optimization has a negligible impact on overall runtime/backpressure performance over the non-AVX2 version.

Remove bit fields from cown status

---

src/rt/sched/cown.h
src/rt/sched/schedulerthread.h
src/rt/sched/status.h

This PR adds a coin flip to artificially overload a running cown before each behaviour step.

Add coin to overload cowns in systematic testing

---

src/mlir/ast-utils.h
src/mlir/generator.cc
src/mlir/generator.h
testsuite/mlir/mlir-parse/call/mlir.txt
testsuite/mlir/mlir-parse/class.verona
testsuite/mlir/mlir-parse/class/mlir.txt
testsuite/mlir/mlir-parse/conditional/mlir.txt
testsuite/mlir/mlir-parse/constant/mlir.txt
testsuite/mlir/mlir-parse/for/mlir.txt
testsuite/mlir/mlir-parse/function/mlir.txt
testsuite/mlir/mlir-parse/nested-conditional/mlir.txt
testsuite/mlir/mlir-parse/nested-while/mlir.txt
testsuite/mlir/mlir-parse/types/mlir.txt
testsuite/mlir/mlir-parse/while-cont-brk/mlir.txt
testsuite/mlir/mlir-parse/while-context/mlir.txt
testsuite/mlir/mlir-parse/while-if/mlir.txt
testsuite/mlir/mlir-parse/while/mlir.txt

Previously, we were treating the module as a special case of class and
lowering a (so far) redundant class representation. This was getting in
the way of simple lowering of methods and nested classes.
This refactory changes how this is done by treating the module as just
another class, and lowering sub-classes, methods and fields in a natural
way. There is no need for a class operation, as the class type is
lowered correctly and is associated with every function via a function
attribute.
Compiler-generated functions (ex. `for` loop's `next`/`has_value`) do
not have a class context. It is debatable if others will need it, and
the intention is to have them declared in Verona code soon enough, in
which case, they will have their classes as an attribute then.
Class types also have gained a …

Refactoring how classes are lowered

---

src/mlir/ast-utils.h
src/mlir/dialect/Typechecker.cc
src/mlir/generator.cc
src/mlir/generator.h
testsuite/mlir/mlir-parse/call/mlir.txt
testsuite/mlir/mlir-parse/class.verona
testsuite/mlir/mlir-parse/class/mlir.txt
testsuite/mlir/mlir-parse/constant/mlir.txt
testsuite/mlir/mlir-parse/for/mlir.txt
testsuite/mlir/mlir-parse/function/mlir.txt
testsuite/mlir/mlir-parse/nested-while/mlir.txt
testsuite/mlir/mlir-parse/while-context/mlir.txt

Implementing field read/write for some simple cases. Not all options covered
yet. We have a few examples that show the mechanism working, but there
are a few cases that are not covered. The main impediment right now is
the viewpoint validation that fails to check some cases.
Before we enbark on a full check of the actual pass, we need to make
sure the types we're generating early (including unknown) will ever be
seen by these passes or the type inference (not implemented yet) will have
cleaned enough of them.
Additional work:
* Adding assignment type from let's declaration, when available by
processing the RHS first and only updating the type if the
declaration has one.
* Created a class-type extraction utility to field_read from lets so we
can find the class extraction point even from …

Adding field_read / field_write

---

src/mlir/generator.cc
src/mlir/generator.h
src/mlir/symbol.h

Simplifying the implementation by only having one lookup and one
update/insert method and making "the other" a wrapper with a default
boolean flag.
Also simplifying the API by making all methods return the element if
inserted/updated/found and use that to avoid multiple redundant lookups
throughout the code.
The main difference is the use of `update` when declaring classes, so
that it is clear we can pre-declare them before they're fully defined
(for example, as a type for some earlier class' member).
Before that logic was hidden through a lookup + insert, and now it
simplifies as just an update.
In the end we have a lot less redundant map searches and a simpler code
to follow.

Simplify Symbol Table Impl/API

---

src/mlir/generator.cc
src/mlir/symbol.h

This is the actual behaviour, so use the right name.

SymbolTable: Rename update to getOrAdd

---

src/rt/ds/stack.h
src/rt/region/region_trace.h
src/rt/test/func/cowngc1/cowngc1.cc
src/rt/test/func/cowngc4/cowngc4.cc
src/rt/test/func/diningphilosophers/diningphil.cc
src/rt/test/func/ext_ref/ext_ref_basic.h
src/rt/test/func/ext_ref/ext_ref_merge.h
src/rt/test/func/ext_ref_freeze/ext_ref_freeze.cc
src/rt/test/func/memory/memory.cc
src/rt/test/func/memory/memory.h
src/rt/test/func/memory/memory_alloc.h
src/rt/test/func/memory/memory_gc.h
src/rt/test/func/memory/memory_iterator.h
src/rt/test/func/memory/memory_merge.h
src/rt/test/func/memory/memory_subregion.h
src/rt/test/func/memory/memory_swap_root.h
src/rt/test/func/noticeboard/noticeboard_basic.h
src/rt/test/func/noticeboard/noticeboard_primitive_weak.h
src/rt/test/func/noticeboard/noticeboard_weak.h
src/rt/test/func/notify/notify.cc
src/rt/test/func/notify/notify_coalesce.h
src/rt/test/func/notify/notify_interleave.h
src/rt/test/func/rememberedset/rememberedset.cc
src/rt/test/harness.h
src/rt/test/perf/ubench/ubench.cc

This adds an extra field to the region meta-data for keeping a stack of additional roots.  These are intended to be references from higher stack frames that must be kept alive during a region gc operation.
The additional roots must be empty if the region is dropped or merged into another region.  The target region of a merge may contain additional roots.

Add additional roots to traced region

---

src/rt/sched/cown.h
src/rt/sched/schedulerthread.h

The systematic log entries now refer to cowns in the form "cown <id>". This makes it easier to search through logs for all of the events that have been logged for a specific cown.

Make cown logs more consistent

---

src/mlir/generator.cc
testsuite/mlir/mlir-parse/variables.verona
testsuite/mlir/mlir-parse/variables/mlir.txt

With a test to make sure we can create nested scope variables with the
same name but access after the scope is still done to the original
variable.

Lexical blocks add variable scope

---

src/mlir/generator.cc
src/mlir/generator.h
testsuite/mlir/mlir-parse/call/mlir.txt
testsuite/mlir/mlir-parse/class/mlir.txt
testsuite/mlir/mlir-parse/conditional/mlir.txt
testsuite/mlir/mlir-parse/for/mlir.txt
testsuite/mlir/mlir-parse/function/mlir.txt
testsuite/mlir/mlir-parse/nested-conditional/mlir.txt
testsuite/mlir/mlir-parse/nested-while/mlir.txt
testsuite/mlir/mlir-parse/types/mlir.txt
testsuite/mlir/mlir-parse/variables/mlir.txt
testsuite/mlir/mlir-parse/while-cont-brk/mlir.txt
testsuite/mlir/mlir-parse/while-context/mlir.txt
testsuite/mlir/mlir-parse/while-if/mlir.txt
testsuite/mlir/mlir-parse/while/mlir.txt

During the type refactoring, the comparison to load a value moved to
`unkTy` which was the wrong way of querying an alloca.
While the real fix is to not need those in the first place, they help
simplify condition/loop lowering. Once we simplify `for` loops, for
example, and we get to a single loop lowering, we should expand it to
carry free variables as arguments to basic blocks, and then we can get
rid of the alloca/store/load mode.
Most test changes are the introduction of loads before calls, but the
re-numbering of SSA values make it look like it's a big thing.
Partially implements #303.
Based on #316.

Fix alloca values not being loaded

---

src/compiler/codegen/builtins.cc
src/compiler/codegen/function.cc
src/compiler/codegen/generator.cc
src/compiler/codegen/generator.h
src/compiler/codegen/ir.h
src/interpreter/bytecode.h
src/interpreter/code.h
src/interpreter/convert.h
src/interpreter/value.cc
src/interpreter/value.h
src/interpreter/value_list.h
src/interpreter/vm.cc
src/interpreter/vm.h
src/rt/region/region_trace.h
testsuite/features/run-pass/tidy-protect.verona

The VM gains two new opcodes, PROTECT and UNPROTECT, which respectively add and remove objects from the shadow root stack of the runtime.
The compiler uses liveness information to insert the operations around every method call. Note that this is very conservative. The compiler makes no attempt to guess whether a reference is in fact in the same region as one of the arguments or not. It just assumes it could and protects everything.
Couple of cleanups and fixes:
- Clarify parameter names of the shadow stack API.
- Fix a bug caused by finalisers, where the value stack grows at unexpected times.
- Add proper support for opcodes with a variable number of arguments. The Print opcode already did this, but in a very ad-hoc way.

Add support for the shadow root stack in the VM

---

src/mlir/ast-utils.h
src/mlir/generator.cc
src/mlir/generator.h

When creating this utility class, I didn't quite know what to expect.
But now, after enough commits, I can see it won't be more than just a
bunch of wrappers.
The ownership model was made "weak" to make sure we don't hold objects
for longer than they need, and don't create cycles in the reference
model. But since we hold nothing in the class itself, and all methods
are static, this will never happen anyway.
Moving to Ast shared pointers avoids all calls to `lock()` during the
interplay between weak_ptr and shared_ptr, and removes the need to
create `ptr` objects for multiple accesses. It also makes debugging the
code easier, as you can print the object with `*ast.get()`, while trying
to lock first won't work on most cases.

AST utils to use Ast instead of WeakAst

---

src/rt/sched/cown.h
src/rt/test/func/notify/notify.cc
src/rt/test/func/notify/notify_empty_queue.h

If the message queue is empty, then notification was not called.
This commit has a test where with a cown that only receives notification
messages. It ensures that messages are consolidated, and
that notification are processed.

Bug fix for notification

---

src/ast/ast.cc
src/ast/ast.h
src/ast/cli.cc
src/ast/cli.h
src/ast/main.cc
src/ast/module.cc
src/ast/module.h
src/ast/pass.h
src/mlir/verona-mlir.cc

This PR adds three things:
1. Comments to all `ast.h` methods, to help clarify what they do and what are the inter-dependencies.
2. A `Pass` class wrapper for the function pointers of each pass to have a name, so that we can print an `after-tree` with a name associated.
3. An `ast_dump` method, for use in debuggers.
It's not possible to create tests yet due to the nature of our (hard-coded) test runner (in CMake).

Three changes to the ast parser: comments on ast.h, new pass.h, ast_dump

---

src/rt/sched/cown.h
src/rt/sched/schedulerthread.h
src/rt/sched/status.h

This is the first step towards implementing the full backpressure system, as described by the TLA+ spec. This is mostly cosmetic, except that prioritization via overloading is a state transition that may occur before a message is processed by a cown. Also, cowns are now lowered to a normal priority when their queue becomes empty and goes to sleep.

Replace backpressure state with priority

---

src/mlir/ast-utils.h
src/mlir/generator.cc
testsuite/mlir/mlir-parse/call.verona
testsuite/mlir/mlir-parse/call/mlir.txt

Invoke is similar to `call`, where the first argument is a `member`
instead of a reference to an object. But the reference to the object is
in the member, together with the method's name.
Adapting the ast-utils methods to work around that made the MLIR
implementation identical and therefore unchanged. Added test for invoke
on existing file.

Implement `invoke` ast node in MLIR

---

src/ast/CMakeLists.txt
src/ast/ast.cc
src/ast/ast.h
src/ast/main.cc
src/ast/sugar.cc
src/ast/sugar.h
src/mlir/generator.cc
src/mlir/verona-mlir.cc
testsuite/mlir/mlir-parse/for-sugar.verona
testsuite/mlir/mlir-parse/for-sugar/mlir.txt
testsuite/mlir/mlir-parse/for/mlir.txt
testsuite/parse/ast-parse/for-sugar.verona
testsuite/parse/ast-parse/for-sugar/ast.txt
testsuite/parse/ast-parse/hygienic-id.verona
testsuite/parse/ast-parse/hygienic-id/ast.txt
testsuite/parse/ast-parse/loop/ast.txt

Adding desugar ast pass with one transformation for replacing `for`
loops as `while` loops with the appropriate API calls. The types used in
the `for` loop are supposed to implement the iterator interfaces that
have methods: has_value, apply and next.
Some helper functions are added to sugar.cc, as it's not clear they will
be useful outside the de-sugaring context, but others were added to
ast.cc, which are available to all passes.
Those are:
* insert_before(child, before): insert `child` into `before`'s parent,
before that node.
* move(ast, child): move `child` to its new parent, `ast`.
* move_before(child, before): same as insert_before, but move.
* move_children(ast, old): move all children from `old` into `ast` and
clear `old` children.
Also, added a hygienic ID per class scope, auto …

De-sugar `for` loops + hygienic ids

---

src/rt/sched/cown.h
src/rt/sched/schedulerthread.h

This PR changes the condition to delay a muted cown. Previously, a cown would not be muted on a thread in the `Prescan`, `Scan`, or `AllInScan`. Now we only delay muting cowns that have the `SCANNED` epoch mark.
This PR also makes a change to rescan the mute map so long as a key in the map has been unmuted as a member of an invalid mute set. This is necessary to ensure that deadlock detection avoids false positives after an incremental scan.

Fix false leak detection of muted cowns

---

src/ast/grammar.peg
testsuite/parse/ast-parse/when/ast.txt

Using a tuple to store the list of arguments to a when block makes
handling it in the rest of the compiler a bit awkward. Singleton
tuples are elided, therefore when blocks with 1 arguments had a
different representation compared to those with more.
It may also help us in the future, when we want to expand the syntax
allowed in when blocks to allow binding the cown to a new name
(eg. `when (x <- E)`). Using a tuple here wouldn't make sense.

Change the grammar of when to not use a tuple.

---

src/mlir/CMakeLists.txt
src/mlir/generator.cc

LLVM was accidentally disabling all warnings, which let a couple of
them sneak into generator.cc
We can re-enable them by setting LLVM_ENABLE_WARNINGS to ON. This was
fixed upstream, so we can get rid of it next time we update.

Fix some warnings in generator.cc

---

src/mlir/generator.h

This is the last warning in the Verona code:
* warning: definition of implicit copy constructor for 'ReturnValue'
is deprecated because it has a user-declared copy assignment operator
All other warnings in the build are in external components.

Remove unused assignment operator

---

testsuite/features/run-pass/tidy-protect.verona

The comment was incorrectly stating that o2 is live, while
simultaneously stating that it is unreachable. This was a simple typo:
o2 is indeed unreachable, whereas o5 is live. The program itself and its
assertions are correct.

Fix a typo in the tidy-protect test comments.

---

src/parser/CMakeLists.txt
src/parser/pretty.cc
src/parser/pretty.h
src/parser/print.cc

Here is the rewrite of the pretty printer to more directly implement the processing of tokens.
Factored out into a separate .cc/.h files to be reusable, if we want this somewhere else in the code.

Pretty printer

---

src/compiler/codegen/descriptor.cc
src/interpreter/bytecode.h
src/interpreter/code.h
src/interpreter/object.cc
src/interpreter/object.h
src/interpreter/vm.cc
testsuite/features/run-pass/match-structural.verona

For every interface, codegen emits the list of subtypes. During
matching, rather than requiring strict equality of descriptors, we
search through the subtypes of the match type looking for the
descriptor of the object being matched on.

Support matching with an interface type.

---

src/compiler/ast.h
src/compiler/codegen/descriptor.cc
src/compiler/codegen/ir.h
src/compiler/freevars.h
src/compiler/intern.cc
src/compiler/intern.h
src/compiler/mapper.cc
src/compiler/mapper.h
src/compiler/parser.cc
src/compiler/printing.cc
src/compiler/resolution.cc
src/compiler/type.h
src/compiler/type_visitor.h
src/compiler/typecheck/capability_predicate.cc
src/compiler/typecheck/constraint.cc
src/compiler/typecheck/infer.cc
src/compiler/visitor.h
src/interpreter/bytecode.cc
src/interpreter/bytecode.h
src/interpreter/code.h
src/interpreter/vm.cc
src/interpreter/vm.h
src/stdlib/builtin.verona
testsuite/demo/run-pass/bank3.verona
testsuite/features/run-pass/match-capability.verona
testsuite/features/run-pass/match-complex.verona
testsuite/features/run-pass/match-primitive.verona

This adds support for matching on primitives (cown, string, U64), capabilities, and union/intersection types.
This is done by:
- Turning String into a primitive, rather than being hardcoded in the compiler
- Add a `MatchCapability` opcode to the VM. The existing `Match` opcode is renamed to `MatchDescriptor`.
- Use a `TypeVisitor` to explore the match pattern, and using boolean operators to decompose complex types.

Widen the set of types that may be used in pattern matching

---

src/rt/object/object.h

They aren't used anywhere. `mark_pending` was identical to
`set_pending` anyway, which does get used. In practice,
`unmark_pending` is actually done with the `set_atomic`/`set_scc`
methods.

Remove the `mark_pending`/`unmark_pending` methods.

---

CMakeLists.txt
devops/ci.yml
devops/nightly.yml

With `RT_TESTS=Off`, we were not adding any `rt_tests` target, but check was still depending on it.
This is what is currently breaking CI in #364.

Fix the use of RT_TESTS in CI.

---

src/rt/sched/cown.h
src/rt/sched/priority.h
src/rt/sched/schedulerthread.h

Remove the `has_token` field from the `Cown` struct. The cown's token message is now tracked using an additional bit in the `bp_state` field.

Track token message in backpressure state

---

CMakeLists.txt
cmake/copyright.cmake
devops/ci.yml
utils/copyright_check.sh

This helps us running `ninja copyright` to check locally without having to rely on the CI or running it by hand. Should work on anything that has `bash` including Windows.
I tested both checks by changing/removing the headers from some files and the output (and exit status) are as expected.

Add copyright/license check to CMake

---

devops/ci.yml
devops/llvm.yml
src/mlir/dialect/VeronaDialect.cc
src/mlir/dialect/VeronaOps.cc
src/mlir/dialect/VeronaOps.h
src/mlir/dialect/VeronaTypes.cc
src/mlir/driver.h
src/mlir/generator.cc
src/mlir/generator.h
src/mlir/symbol.h
testsuite/mlir/mlir-parse/call/mlir.txt
testsuite/mlir/mlir-parse/class/mlir.txt
testsuite/mlir/mlir-parse/conditional/mlir.txt
testsuite/mlir/mlir-parse/constant/mlir.txt
testsuite/mlir/mlir-parse/dialect/mlir.txt
testsuite/mlir/mlir-parse/for-sugar/mlir.txt
testsuite/mlir/mlir-parse/for/mlir.txt
testsuite/mlir/mlir-parse/function/mlir.txt
testsuite/mlir/mlir-parse/lookup/mlir.txt
testsuite/mlir/mlir-parse/nested-conditional/mlir.txt
testsuite/mlir/mlir-parse/nested-while/mlir.txt
testsuite/mlir/mlir-parse/subsumption/mlir.txt
testsuite/mlir/mlir-parse/types/mlir.txt
testsuite/mlir/mlir-parse/variables/mlir.txt
testsuite/mlir/mlir-parse/while-cont-brk/mlir.txt
testsuite/mlir/mlir-parse/while-context/mlir.txt
testsuite/mlir/mlir-parse/while-if/mlir.txt
testsuite/mlir/mlir-parse/while/mlir.txt

The new commit fixes a problem on MSVC builds and doesn't seem to break anything upstream either, with the specific commit passing on many buildbots. Appropriate changes to the MLIR code to match included.
Additional changes:
* We're not building debug versions of LLVM anymore. We don't use them, they were huge and had random build failures on Windows. It's better to build a custom debug version for what we need locally when we do need than having multiple cached builds on storage that we never use.
* Moved LLVM's default branch from "master" to "main"
* Building Clang in addition to MLIR. The FFI code will depend on that, so we need the libraries in there.
There is still one build failure (Windows) because of a pegmatite library export issue that @mjp41 has identified. Once that's fixed, …

Move LLVM to dd2dac2fd07

---

src/rt/sched/behaviour.h
src/rt/sched/cown.h
src/rt/sched/schedulerthread.h

Each scheduler thread would previously manage a map to track which cowns had been muted. The keys in this map were the "mutor", which is the high priority cown that received a message from the set of cowns that were muted. The mute map managed by each scheduler thread has been replaced by a message to the mutor containing the set of cowns that have been muted. This mechanism is simpler than the mute map, removes the need for frequent mute map scans, and it should fix possible sources of deadlock from the mute maps.

Replace mute map with message to mutor

---

devops/llvm-anybuild.yml

I added a service principal via variable group to the AnyBuild build for LLVM -- this service principal is something we'd be comfortable handing off, but have just temporarily stored in a keyvault that is under our subscription. 
These updates should use that principals service credentials to consume anybuild.

Use a service principal that has access to AnyBuild to authenticate in CI

---

testsuite/run_command.cmake
testsuite/verona-parser.cmake

Output what is being done, so that it is easier to reproduce outside the test harness.

Minor improvements with test harness

---

src/rt/object/object.h
src/rt/region/freeze.h
src/rt/region/immutable.h
src/rt/region/region.h
src/rt/region/region_arena.h
src/rt/region/region_trace.h
src/rt/region/rememberedset.h
src/rt/sched/base_noticeboard.h
src/rt/sched/cown.h
src/rt/sched/epoch.h
src/rt/sched/multimessage.h
src/rt/sched/noticeboard.h
src/rt/sched/schedulerthread.h
src/rt/sched/threadpool.h
src/rt/test/harness.h
src/rt/test/systematic.h

Systematic testing uses std::endl for printing, but it is otherwise not used.
Added Systematic::endl to avoid pulling in link-time dependencies towards <ostream> elements when not using systematic testing.
This allows using the Verona runtime in environments that don't support <ostream>.

Removed the dependencies of the runtime on std::endl outside of systematic testing

---

devops/llvm-anybuild.yml

- use yaml parameters instead of variables for the values settable at queue time
- remove the "validate agents" step (and instead instruct the AnyBuild process to dynamically fetch available agents)
- changed the "validate all remoted" step to instead print out some AnyBuild stats

Update AnyBuild pipeline

---

src/rt/sched/base_noticeboard.h
src/rt/sched/threadpool.h
src/rt/test/systematic.h

The systematic PRNG was previously declared as thread_local, and only one of the PRNGs would be seeded on setup. This makes the PRNG global and uses a spinlock to allow multiple threads to receive the next random number.

Make the PRNG global

---

devops/llvm-anybuild.yml

- update GOOD_HASH to `9f33943ee01`
- update cmake to build clang + mlir
- make 'create package' deterministic by specifying a canned `mtime`
- update pool definition to demand an agent tailored for the requested build type (Release vs Debug)
- delete the produced tarball after publishing it

[llvm-anybuild] Update to match the LLVM CI pipeline

---

devops/llvm-anybuild.yml

This helps keep process fingerprints stable across builds.

[llvm-anybuild] Use an empty environment when running a build

---

devops/llvm-anybuild.yml

Without passing PATH through, the build fails to find `git`(which it needs to determine version) and produces the following warning:
```
CMake Warning at /home/AnyBuild/azp-verona/_work/2/s/llvm/cmake/modules/VersionFromVCS.cmake:49 (message):
Git not found.  Version cannot be determined.
Call Stack (most recent call first):
/home/AnyBuild/azp-verona/_work/2/s/llvm/cmake/modules/GenerateVersionFromVCS.cmake:23 (get_source_info)
/home/AnyBuild/azp-verona/_work/2/s/llvm/cmake/modules/GenerateVersionFromVCS.cmake:45 (append_info)
```

[llvm-anybuild] Add PATH to the build environment

---

src/rt/sched/schedulerthread.h
src/rt/sched/threadpool.h

This introduces two changes to systematic testing.
*  Using guard functions to build condition variables without an
explicit notion of waiting.
* Use a step count so we perform fewer operations on the fast path.

Simplify systematic testing

---

devops/ci.yml
devops/nightly.yml

Seems the previous Ubuntu version (18.04) broken something with ASAN this week, and moving to 20.04 seems to fix it. It was about time to move anyway, so here it goes.
The problems we found were so far fetching (old `veronac`, new `verona-mlir` and `verona-interop`), that it's very unlikely they're from anything remotely similar. Problem in the system is more likely than in our code.
Both CI and nightly were fixed by this commit, with nightly back to the previous failures that we're still investigating (#436).

Move CI to Ubuntu 20 to fix ASAN build

---

devops/llvm-anybuild.yml
devops/steps/git-shallow-clone.yml
devops/steps/print-anybuild-stats.yml
devops/steps/tar-and-upload.yml

The pipeline has the following job dependencies:
```
Configure
├── LLVM-linux
├── LLVM-macOS
└── LLVM-windows
```
The `Configure` job sets an output variable named `LLVM_COMMIT` to either to the value of the `$(GOOD_HASH)` pipeline variable (if set) or the commit hash of the llvm-project submodule currently checked into this repo.
The subsequent jobs build the `LLVM_COMMIT` commit of the `llvm-project` repo on Linux, Windows, and macOS.   They all produce an installation tarball and optionally upload it to blob storage.
On Linux and Windows, the build is wrapped with AnyBuild to provide distribution and caching on top of the native build.

Add AnyBuild pipeline

---

src/rt/cpp/lambdabehaviour.h
src/rt/test/func/ext_ref/ext_ref_basic.h
src/rt/test/func/notify/notify_basic.h
src/rt/test/func/runtimepause/runtimepause.cc

This moves a couple of the existing unit tests to use the new C++ Lambda API.  This generally is a good compression of the examples.  Gradually, we should move more across.  This PR was enough for me today ;-)

Move some unit tests to Lambda

---

cmake/clangformat.cmake
external/CMakeLists.txt

One fixes finding clang-format, the other fixes building on any platform where there isn't an LLVM download.

Two small fixes for FreeBSD

---

src/mlir/consumer.cc
src/mlir/generator.cc
src/mlir/generator.h
testsuite/verona-mlir/arithmetic.out/stdout.txt
testsuite/verona-mlir/arithmetic.verona
testsuite/verona-mlir/struct.out/stdout.txt
testsuite/verona-mlir/struct.verona
testsuite/verona-mlir/using.out/stdout.txt
testsuite/verona-mlir/using.verona

This commit adds signed/unsigned integer types and moves all cast
operations to the standard library implementation. For now, it's
implemented on the tests themselves, but that implementation should move
to `stdlib` and the tests should include that.
From now on, we assume that all casts and type promotions will happen at
the AST level and we'll get the correct types for all arithmetic
operations, so this commit also adds a few asserts  to make sure that's
true.
See `testsuite/verona-mlir/arithmetic.verona` for an idea how arithmetic
functions will look like. Soon, inline MLIR calls will change syntax
(probably something like @std.addi instead of "std.addi") and we can
move the implementation to the standard library.

Supporting signed/unsigned types, no auto-cast

---

devops/llvm-anybuild.yml
devops/nightly.yml
devops/steps/linux/anybuild.yml
devops/steps/linux/dependencies.yml
devops/steps/linux/test.yml
devops/steps/tar-and-upload.yml
devops/vars/anybuild-vars.yml
devops/vars/llvm-vars.yml
external/CMakeLists.txt
src/rt/CMakeLists.txt

The only functional change should be the addition of the new stage.
This PR also includes a syntactic change which breaks up the nightly pipeline into the following stages
- Linux (Verona)
- Linux (Verona+LLVM)
- Windows (Verona)
- macOS (Verona)
Having stages is convenient because the ADO GUI allows for selecting which stages to execute when enqueuing a new build (and so, it becomes easy to run partial validations).

[nightly.yml] Add a new stage for building Verona+LLVM at once on Linux

---

src/mlir/consumer.cc
src/mlir/consumer.h

This allows us to return at any time from the post methods while making
sure we unwind the stack correctly on all cases.
For now there's only one case where this is beneficial, but it's a good pattern to keep.

Use automatic cleanup for symbol stack pop

---

src/mlir/consumer.cc
src/mlir/consumer.h

This commit implements class initialisation (fields, types, etc) to a
single class that inhabits a stack during declaration, then moves to an
unordered map to be used during the definition phase.
Both declaration stack and definition map are on the same type, so it's
a simple move once the object is finalised. With this, we reduce the
number of shared state between declaraiton and definition and also
simplify the field access logic considerably.
No tests changed, which is a good sign.

Move class initialisation into a single struct

---

devops/ci.yml
experiments/process_sandbox/CMakeLists.txt
experiments/process_sandbox/include/process_sandbox/helpers.h
experiments/process_sandbox/include/process_sandbox/platform/README.md
experiments/process_sandbox/include/process_sandbox/platform/sandbox_seccomp-bpf.h
experiments/process_sandbox/include/process_sandbox/platform/shm_posix.h
experiments/process_sandbox/src/child_malloc.h
experiments/process_sandbox/src/library_runner.cc
experiments/process_sandbox/src/libsandbox.cc
experiments/process_sandbox/tests/poller.cc

- GCC and libstdc++ requires libatomic for 64-bit compare and exchange,
so link it when compiling with GCC.
- Wrap the clang-specific pragmas for silencing warnings in macros so
that they're only used when compiling with clang.
- Don't use a FreeBSD-libc-specific snmalloc option on non-FreeBSD
platforms.
- Run the process-sandbox tests if snmalloc changes.  This should make
it easier for Matthew to test new snmalloc imports.

Fix the Linux build with GCC and enable CI:

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

As mentioned in #463 
A devcontainer in the directory .devcontainer allows VSCode to launch and mount a docker container which you can work from.
This comes with all dependencies pre-installed, you'll just have to build the container once, the first time you open it (and every time it changes).
I've tested compilation, verona compiles in it.
```
[main] Building folder: verona verona
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /workspaces/verona/build --config Debug --target verona -j 18 --
[build] [1/2   0% :: 0.000] Re-checking globbed directories...
[build] [1/17   5% :: 0.120] Creating directories for 'external'
[build] [2/17  11% :: 0.159] No download step for 'external'
[build] [4/17  17% :: 0.200] No update step for 'external'
[build] [4/17  23% :: 0.205] …
```

Added .devcontainers

---

docs/internal/capabilities.md

This may be incomplete, but I'm not sure how to match the pony tutorial sections with Verona if some of the types are missing and the other's semantics are slightly different. For example, I haven't added a section on viewpoints because I'm not sure how that'll work.
I'd gladly to accept proposals for entire sections if you're feeling charitable.

Adding capabilities document

---

src/interop/CXXBuilder.h
src/mlir/verona-mlir.cc
testsuite/verona-mlir/arithmetic.out/stdout.txt
testsuite/verona-mlir/call.out/stdout.txt
testsuite/verona-mlir/declaration-order.out/stdout.txt
testsuite/verona-mlir/empty-class.out/stdout.txt
testsuite/verona-mlir/example.out/stdout.txt
testsuite/verona-mlir/function.out/stdout.txt
testsuite/verona-mlir/main.out/stdout.txt
testsuite/verona-mlir/string.out/stdout.txt
testsuite/verona-mlir/struct.out/stdout.txt
testsuite/verona-mlir/tuple.out/stdout.txt
testsuite/verona-mlir/using.out/stdout.txt

Brings LLVM forward 4 months, across versions, and has no noticeable differences in the API (clang or MLIR), which is incredible.

Upgrade LLVM to a19747ea739

---

src/rt/object/object.h

Clarifying a comment on the object header after me assuming the region metadata was 64-bits when in fact it's pointer sized.

Clarify size comment on object

---

CMakeLists.txt
devops/nightly.yml
external/CMakeLists.txt

When asking to build LLVM or re-use an already built directory, CMake
forced users to turn off VERBOSE_LLVM_DOWNLOAD, which was on by default
and emitted a confusing error message.
To avoid having to pass -DVERBOSE_LLVM_DOWNLOAD=OFF on the other two
ways to build Verona, we just assume that, when users set those
variables, they really don't need to download it, too.
Keeping the error message when both build and reuse options are set, as
neither are set by default and it would clearly be an error.

User friendly LLVM option

---

src/rt/sched/schedulerthread.h
src/rt/sched/spmcq.h
src/rt/sched/threadsyncsystematic.h

These were found running tests with UBSAN and a specific random seed
that made tests fail.
Hopefully this will reduce the issues on the MacOS nightly runs. But it
also gives us a way to debug further issues if they arise.
All debug was done on Linux, so YMMV on the effects on Macs.
Co-authoredr-by: Matthew Parkinson <mattpark@microsoft.com>

Fixes a few UB on the run-time

---

src/mlir/consumer.cc
src/mlir/consumer.h

We were treating TypeName as a Type, when actually both are NodeDef.

Fix UB on consumeType

---

devops/llvm-anybuild.yml
devops/llvm.yml
external/CMakeLists.txt
src/mlir/CMakeLists.txt

We needed EH/RTTI before because we were using a peg library that needed
EH and to make linking easier with the rest of the compiler, we forced
EH on LLVM.
This is no longer true, so we just disable that in the MLIR directory,
which is enough to drop the requirement for LLVM.
Right now, nothing will change because the LLVM we have from the blob
has EH/RTTI. But once we build a new one (or move to an actual package
manager), it will work out-of-the box.
Tested locally with pre-built LLVM (both with and without EH/RTTI) and in-tree builds of LLVM.

Remove EH/RTTI from LLVM builds

---

src/interop/CXXQuery.h
src/interop/Compiler.h
src/interop/FS.h
src/interop/verona-interop.cc

Running `verona-interop` through ASAN & UBSAN & LSAN has produced issues that are now fixed by this PR.
This allows us to turn on ASAN on all builds (but not UBSAN, which still has issues in the parser).

Address Sanitizer fixes

---

CMakeLists.txt
devops/ci.yml
devops/nightly.yml
src/CMakeLists.txt
src/rt/CMakeLists.txt

Change USE_ASAN option to SANITIZER, so that we can choose any sanitizer
to run on local builds or CI.
Runs ASAN on both commit CI and nightly, so we can catch errors earlier.
Not running UBSAN yet because some errors in the parser are still
failing and there may be some spurious run-time errors that need fixing
before turning it on.
But from this commit onwards, anyone can use any sanitizer (even
combining them with -DSANITIZER="address,undefined,leak") on a local
build for all programs, not just ASAN on the run-time.

Generic sanitizer run on CI

---

devops/ci.yml
devops/nightly.yml
src/CMakeLists.txt

Re-enable all sanitizers' tests in CI and Nightly.

UBSAN - vptr because of LLVM's no-rtti

---

devops/nightly.yml

Mac nightly is having some trouble with the runtime and pthread
libraries that we can't reproduce on local machines. Matt suggested we
disable asserts and early tests confirmed that this doesn't fail after
two rounds.
It could be lock or not, but technically we don't need asserts on all
platforms, especially when using the same compiler (clang).
If/when we find and fix the actual problem (or move to a newer platform)
we can turn this back on.

Disable assert on mac

---

external/CMakeLists.txt

Otherwise, when building Verona + LLVM all together, the build type for LLVM is set to the same build type as specified for Verona.  Consequently, it's not possible to at once build Verona in Debug and LLVM in Release.

[cmake] Allow LLVM_EXTRA_CMAKE_ARGS to override CMAKE_BUILD_TYPE

---

src/rt/pal/cpu.h
src/rt/pal/threading.h
src/rt/pal/threadpoolbuilder.h
src/rt/test/func/external_threading/verona_external_threading.h
src/rt/test/harness.h
src/rt/test/threadping.h

This allows custom platforms to reuse the harness code. Updated comments to hopefully address confusion from the internal/external naming.

Changed std::thread usage in harness to verona::InternalThread

---

docs/explore.md

Links should now work from both https://microsoft.github.io/verona/explore.html and https://github.com/microsoft/verona/blob/master/docs/explore.md

replace a few relative links with absolute ones

---

src/rt/pal/cpu.h
src/rt/pal/threadpoolbuilder.h
src/rt/test/func/external_threading/verona_external_threading.h

The topology was not working correctly if it was run twice.  This change
makes it static, and thus does not need to query the CPUs repeatedly.
While writing some new tests I observed that after the first run, when the
runtime restarted, all the threads had been affinitized to a single core. This
makes the topology static, and just initialises it on first use.
I also made the vector an embedded field for simpler memory/lifetime
management.

Fix Topology to work with repeated runtime starts

---

src/rt/ds/bag.h
src/rt/test/func/bag/bag.cc

A bag is an vector-like data structure using aligned block which is optimised for constant time insertion and removal.
Removal is O(1) because a removed item will leave a hole in the bag rather than shifting remaining items down like in a bag. To reduce fragmentation which can occur with deallocation churn, the bag maintains a freelist which is threaded through the holes left in the bag. Insertion of new items will first query the freelist to see if a hole can be reused, otherwise items are bump allocated.
This data structure is useful for tracking objects in regions -- such as one which uses reference counting -- where efficient alloc/dealloc is necessary.

Add bag data structure

---

experiments/process_sandbox/README.md
experiments/process_sandbox/include/process_sandbox/platform/sandbox_seccomp-bpf.h
experiments/process_sandbox/tests/CMakeLists.txt
experiments/process_sandbox/tests/sandbox-modify-pagemap.cc
experiments/process_sandbox/tests/sandboxlib-modify-pagemap.cc

On Linux, where you don't have Capsicum or anything usefully equivalent,
you can't drop write permissions on a file.  We can fudge this using
fdfs to reopen the shared memory region in read-only mode before we mmap
it.  This prevents the attacker from being able to mprotect the shared
pagemap read-write.
There's now a test that checks for this.  This fixes the last known
security vulnerability, just in time for Saar to find some new ones next
week.

Fix the last known security issue in the process-sandbox code.

---

src/rt/ds/bag.h
src/rt/test/func/bag/bag.cc

The `BagThin` data structure is a bag where each element contains only a `T*`. Unlike `Bag`, where elements can have an additional field, `ThinBag` is optimised to be space-efficient when this is not necessary.
This change refactors the original bag implementation into a common base class which is then composed into concrete `Bag` 
and `BagThin` implementations.

Add `BagThin` data structure

---

src/rt/cpp/promise.h
src/rt/test/func/promise/promise.cc

This PR adds some functionality to the promises implementation in the verona runtime.
It manages the case in which the promise returns a smart pointer and it allows getting the raw promise pointer out of the read endpoint.

Enhance promises

---

experiments/process_sandbox/CMakeLists.txt
experiments/process_sandbox/include/process_sandbox/callback_numbers.h
experiments/process_sandbox/include/process_sandbox/callbacks.h
experiments/process_sandbox/include/process_sandbox/netpolicy.h
experiments/process_sandbox/include/process_sandbox/platform/child_process_vfork.h
experiments/process_sandbox/include/process_sandbox/platform/sandbox_capsicum.h
experiments/process_sandbox/include/process_sandbox/platform/syscall_context_freebsd.h
experiments/process_sandbox/include/process_sandbox/platform/syscall_context_linux.h
experiments/process_sandbox/include/process_sandbox/sandbox.h
experiments/process_sandbox/src/library_runner.cc
experiments/process_sandbox/src/libsandbox.cc
experiments/process_sandbox/tests/CMakeLists.txt
experiments/process_sandbox/tests/net-test-helpers.h
experiments/process_sandbox/tests/sandbox-curl.cc
experiments/process_sandbox/tests/sandbox-network.cc
experiments/process_sandbox/tests/sandboxlib-curl.cc
experiments/process_sandbox/tests/sandboxlib-fake-open.cc
experiments/process_sandbox/tests/sandboxlib-network.cc

This proxies the three POSIX socket functions that access the global
namespace:
- bind
- connect
- getaddrinfo (which could be used to implement the legact IPv4
interfaces)
These are passed through a policy layer that allows sandbox consumers to
either:
- Block them unconditionally.
- Allow them to work with any address.
- Add an interposer that implements the function based on some custom
policy.
This makes it possible to enforce policies such as 'this sandbox may
establish outbound connections to microsoft.com:80 but nothing else' by
interposing on the `getaddrinfo` call to record the valid addresses for
this address / service combination and allowing `connect` only for those
addresses.
The callback infrastructure was starting to be a bit unwieldy, so this
has been refactored to use …

Add network support to sandboxes.

---

src/rt/CMakeLists.txt
src/rt/pal/semaphore.h
src/rt/sched/schedulerthread.h
src/rt/sched/threadpool.h
src/rt/sched/threadsync.h
src/rt/sched/threadsyncsystematic.h
src/rt/test/systematic.h

Prior to this PR, `unpause` would take a lock to ensure that wake-ups weren't lost.  This is unfortunately a problem if an external signal/interrupt causes the runtime to `unpause`, while the thread it signalled/interrupted is holding the lock.
This code changes the implementation to use a custom spin lock and semaphores to enables `unpause` to not require the lock, but instead notifies the thread holding the lock that it must wake all threads up on exit from the lock.

Make unpause signal safe

---

src/rt/region/region_rc.h

Our nightly builds have been failing on MacOS release and this is the error. I'm not sure why other release builds in Linux and Windows are not picking this up.
https://dev.azure.com/ProjectVeronaCI/Project%20Verona/_build/results?buildId=3462&view=logs&j=27c02e5f-1e08-5ff5-4535-96d1b952e7df&t=27fecc53-61b6-5aa3-75d5-66d0e428ef1b&l=34

Fix unused variable warning in release mode

---

src/rt/region/region_rc.h

Some arguments are used in debug settings, others in the side-effects of
functions they're called with, others are just part of the public API
and are trully unused arguments, but we can't remove them from the
function signature.
This fixes a broken Mac build for the last week.

Silence unused argument with UNUSED

---

src/rt/sched/cown.h
src/rt/sched/priority.h
src/rt/sched/threadpool.h
src/rt/sched/threadstate.h

Fix a few initialisers to ensure that we can constinit the thread pool.  This removes some C++ guard checks from fast paths.

Ensure Thread Pool does not have a guard.

---

src/rt/CMakeLists.txt
src/rt/sched/cown.h
src/rt/sched/multimessage.h
src/rt/sched/threadpool.h
src/rt/sched/threadsync.h

This PR changes the way the verona runtime acquires cowns. When scheduling a behaviour, the runtime acquires all the idle cowns and enqueues the multimessage on the queues of the busy ones. The multimessage has an atomic counter that gets decrement every time a new cown is available. The scheduler thread that last decrements this counter in run_step() also executes the behaviour.

Acquire all cowns at the beginning

---

experiments/process_sandbox/include/process_sandbox/path.h
experiments/process_sandbox/src/libsandbox.cc
experiments/process_sandbox/tests/path.cc

bug found by @saaramar.
This is not exploitable, because the `/..` doesn't exist, but it may
hide other bugs.

Fix missing check for path canonicalisation.

---

src/rt/CMakeLists.txt
src/rt/pal/semaphore.h
src/rt/sched/cown.h

The semantics of AcquireAll appears superior in almost every way to the
original chain of acquiring cowns.  This
commit removes the original semantics.

Remove original acquire one

---

experiments/process_sandbox/src/libsandbox.cc

Add some deterministic initialisation to a buffer that is populated with
a variable-length attacker-controlled structure.
Fixes #561

[process-sandbox] Defence in depth

---

src/rt/cpp/cown.h
src/rt/cpp/when.h
src/rt/test/perf/banking/verona_banks.cc
src/rt/test/perf/dining_phil/verona_dining_phil.cc

This introduces a namespace for the verona C++ api:
verona::cpp
It also fixes a couple of move/copy constructor/operators.

Improved API for CPP

---

src/rt/sched/schedulerthread.h

The variable `total_cowns` should be the length of the per-thread cown list.
This is not the case, this commit checks that this is the case, and correctly
updates it.

Fix `total_cowns` invariant

---

src/rt/cpp/cown.h
src/rt/cpp/when.h
src/rt/test/perf/banking/verona_banks.cc

The previous implementation required a lot of copies of `cown_ptr` that resulted in potentially poor performance.  This implementation does not suffer from that problem as it uses a "univeral reference" for each cown to enable passing without causing decref and increfs.

Optimise the RC for cown_ptr

---

src/rt/cpp/lambdabehaviour.h
src/rt/cpp/vbehaviour.h
src/rt/sched/cown.h
src/rt/sched/multimessage.h

Prior to this commit the multimessage was composed of three allocations, the body, the cowns array and the behaviour/closure to execute.  This PR merges the three structures into a single more complex allocation. On @theodus's perf-con-ubench, we see an 18% improvement in message flow.  
It also includes two small code tidies.

Consolidate allocation of message body

---

src/rt/sched/multimessage.h

This is not true due to the stub message.  
A future PR will add comments, and add more to CI to detect assertion failures.  This is minimal to unblock @hlef

Remove assertion that is not true.

---

src/rt/ds/dllist.h
src/rt/pal/threadpoolbuilder.h
src/rt/sched/base_noticeboard.h
src/rt/sched/core.h
src/rt/sched/corepool.h
src/rt/sched/cown.h
src/rt/sched/schedulerlist.h
src/rt/sched/schedulerthread.h
src/rt/sched/threadpool.h
src/rt/sched/threadstate.h
src/rt/test/perf/smallbank/smallbank.cc

Introducing the `Core` layer in the Verona Runtime scheduler.
Cores hold the cown queues while SchedulerThreads are assigned to a core.
This refactoring enables to add new scheduler threads as needed during the execution of the runtime.

Decoupling SchedulerThreads & Cown queues

---

src/rt/ds/dllist.h
src/rt/sched/corepool.h
src/rt/sched/cown.h
src/rt/sched/schedulerlist.h
src/rt/sched/schedulerthread.h
src/rt/sched/threadpool.h
src/rt/sched/threadstate.h
src/rt/sched/threadsync.h
src/rt/test/func/simp1/simp1.cc
src/rt/test/func/simp2/simp2.cc
src/rt/test/func/simp3/simp3.cc
src/rt/test/func/simp4/simp4.cc
src/rt/test/func/simp5/simp5.cc
src/rt/test/func/simp6/simp6.cc
src/rt/test/harness.h

Overall, reduces the amount of reference count required on a cown from one per message to one per scheduler queue.

Some refactoring of reference count manipulation

---

devops/steps/linux/anybuild.yml

To improve joins of AnyBuild telemetry with ADO telemetry.

Pass through additional ADO env vars to AnyBuild

---

CMakeLists.txt
src/lang.cc
src/lang.h
src/main.cc

This reduces the compile time by around 20% as the latest Trieste does not include CPP::CLI in the main header.

Update to latest trieste version

---

spec/lexical.md
spec/spec.md

This explains the Verona language comment syntax.
Tests for this section have already been added as part of #664.

Add comment section to specification
